spring:
  datasource:
    url: jdbc:sqlite:memory
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: false
